name       : perl-cpan-changes
version    : 0.400002
release    : 1
source     :
    - https://github.com/metacpan/CPAN-Changes/archive/v0.400002.tar.gz : 55845a0b8f1d5283b6311d8fb0aab8e423a098dca5e26fd3ee6d8e81049fa50a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : CPAN::Changes - Read and write Changes files
description: |
    It is standard practice to include a Changes file in your distribution.
    The purpose the Changes file is to help a user figure out what has
    changed since the last release.
 
    People have devised many ways to write the Changes file. A preliminary
    specification has been created (CPAN::Changes::Spec) to encourage module
    authors to write clear and concise Changes.
 
    This module will help users programmatically read and write Changes
    files that conform to the specification.
#builddeps  :
setup      : |
    # include distar.pm module needed for this to build.
    mkdir -p $workdir/Distar/lib
    cp $pkgfiles/Distar.pm $workdir/Distar/lib/Distar.pm
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install